import type {
  ArticleApplicability,
  ArticleStance,
  RunStage,
  RunStatus,
} from './contracts'

export const UI_TEXT = {
  common: {
    unavailable: 'Unavailable',
    dash: '—',
    retry: 'Retry',
    yes: 'Yes',
    no: 'No',
    original: 'Original',
    claim: 'Claim',
    article: 'Article',
    evidence: 'Evidence',
    sectionUnavailable: 'Section unavailable',
    spanUnavailable: 'Span unavailable',
    duration: {
      seconds: (seconds: number) => `${seconds.toFixed(1)}s`,
      minutes: (minutes: number, seconds: number) =>
        `${minutes}m ${String(seconds).padStart(2, '0')}s`,
    },
  },
  brand: {
    name: 'EvidenceGap',
    subtitle: 'Statement evidence analysis',
  },
  header: {
    newAnalysis: 'New Analysis',
    openRecentRuns: 'Open Recent Runs',
    recentRuns: 'Recent Runs',
    status: {
      running: 'Analysis running',
      failed: 'Run needs attention',
      loaded: 'Run loaded',
      ready: 'Ready for analysis',
    },
  },
  drawers: {
    newAnalysis: 'New Analysis',
    closeNewAnalysis: 'Close New Analysis',
    recentRuns: 'Recent Runs',
    closeRecentRuns: 'Close Recent Runs',
  },
  analysisForm: {
    eyebrow: 'New analysis',
    title: 'Analyze a biomedical statement',
    statementLabel: 'Biomedical Statement',
    statementPlaceholder:
      'Enter one or more biomedical claims or an argument…',
    languageLabel: 'Output Language',
    submit: 'Analyze statement',
    submitting: 'Creating run…',
    validation: 'Enter a biomedical statement to analyze.',
    languages: [
      { value: 'English', label: 'Original English' },
      { value: '繁體中文（台灣）', label: '繁體中文（台灣）' },
      { value: '简体中文', label: '简体中文' },
      { value: '日本語', label: '日本語' },
    ],
  },
  workspace: {
    loadingRun: 'Loading analysis run',
    loadingRunDescription: 'Retrieving the current backend state…',
    runNotFound: 'Run not found',
    runLoadFailed: 'Run could not be loaded',
    resizePanels: 'Resize graph workspace and details panel',
  },
  history: {
    eyebrow: 'Workspace',
    title: 'Recent Runs',
    loading: 'Loading recent analyses…',
    loadFailed: 'Could not load Recent Runs',
    emptyTitle: 'No analyses yet',
    emptyDescription:
      'Your completed and in-progress runs will appear here.',
    metrics: {
      claims: 'Claims',
      gaps: 'Gaps',
      time: 'Time',
    },
  },
  graph: {
    eyebrow: 'Claim graph',
    noSelection: 'No analysis selected',
    noSelectionDescription:
      'Submit a biomedical statement or open a recent analysis.',
    focusModeLabel: 'Graph focus mode',
    focusModes: {
      all: 'All',
      gaps: 'Gaps',
      conflicts: 'Conflicts',
    },
    layingOut: 'Laying out argument graph…',
    layoutErrorFallback: 'Unknown graph layout error',
    unavailable: 'Argument graph unavailable',
    noClaims: 'No claims in this analysis',
    noClaimsDescription:
      'The backend presentation contains no Claim nodes to display.',
    claim: (claimNumber: number) => `Claim ${claimNumber}`,
    claimAria: (claimNumber: number, text: string) =>
      `Claim ${claimNumber}: ${text}`,
    inferenceStep: (stepNumber: number) => `Inference Step ${stepNumber}`,
    inferenceAria: (stepNumber: number) =>
      `Inference step ${stepNumber}`,
    inferenceRelation: (premiseCount: number) =>
      `${premiseCount} premise${premiseCount === 1 ? '' : 's'} → 1 conclusion`,
    retrievedTopArticles: 'Retrieved Top Articles',
    articleCounts: (
      support: number,
      refute: number,
      insufficient: number,
    ) => `S ${support} · R ${refute} · I ${insufficient}`,
    terminalClaim: 'Terminal claim',
  },
  details: {
    eyebrow: 'Analysis workspace',
    title: 'Details',
    tabListLabel: 'Analysis details',
    tabs: {
      overview: 'Overview',
      inspect: 'Inspect',
      run: 'Run',
    },
    noAnalysisTitle: 'No analysis selected',
    noAnalysisDescription:
      'Create a run or select one from Recent Runs.',
    nothingToInspectTitle: 'Nothing to inspect yet',
    nothingToInspectDescription:
      'Inspection becomes available after a successful analysis.',
    noRunTitle: 'No run selected',
    noRunDescription:
      'Run progress, localization, exports, and technical details will appear here.',
    originalStatement: 'Original Statement',
    methodologicalBoundary: 'Methodological Boundary',
    methodologicalBoundaryItems: [
      'Only summarizes the retrieved Top Articles.',
      'Not a systematic review.',
      'Not a clinical recommendation.',
      'Not final medical truth.',
    ],
    sourceDepth: (sourceDepth: number, articleTopK: number) =>
      `Source depth: ${sourceDepth}; article top K: ${articleTopK}.`,
    execution: 'Execution',
    created: 'Created',
    output: 'Output',
    duration: 'Duration',
    runId: (runId: string) => `Run ID: ${runId}`,
  },
  summary: {
    eyebrow: 'Result overview',
    pending: 'Analysis pending',
    pendingDescription:
      'Claim Evidence and Inference Integrity will appear after a successful run.',
    complete: 'Analysis complete',
    headline: (
      claims: number,
      supported: number,
      insufficient: number,
      gaps: number,
    ) =>
      `${claims} claims · ${supported} supported · ${insufficient} insufficient · ${gaps} ${gaps === 1 ? 'gap' : 'gaps'}`,
    metricsLabel: 'Analysis summary metrics',
    metrics: {
      claims: 'Claims',
      supported: 'Supported',
      insufficient: 'Insufficient',
      detectedGaps: 'Detected gaps',
    },
    secondary: {
      refuted: (count: number) => `${count} refuted`,
      conflicted: (count: number) => `${count} conflicted`,
      errors: (count: number) => `${count} errors`,
    },
    terminalConclusions: 'Terminal Conclusions',
    terminalUnavailable:
      'Two-axis terminal status unavailable for this Run.',
    noTerminalConclusions: 'No terminal conclusions.',
    integrity: {
      claimsIntact: 'Claims with intact inference',
      claimsGapped: 'Claims with gapped inference',
      stepsIntact: 'Inference steps intact',
      stepsGapped: 'Inference steps gapped',
    },
  },
  claims: {
    title: 'Claims',
    selectSpan: (
      overlapping: boolean,
      text: string,
    ) => `Select ${overlapping ? 'overlapping claim' : 'claim'}: ${text}`,
  },
  evidenceBalance: {
    title: 'Evidence Balance',
    articleCount: (count: number) =>
      `${count} article${count === 1 ? '' : 's'}`,
    boundary: 'Retrieved Top Articles distribution',
    aria: (support: number, refute: number, insufficient: number) =>
      `${support} supporting, ${refute} refuting, and ${insufficient} insufficient articles`,
    supporting: 'Supporting',
    refuting: 'Refuting',
    insufficient: 'Insufficient',
  },
  articles: {
    rankedTitle: 'Ranked Articles',
    boundary: 'Retrieved Top Articles for this Claim',
    groups: {
      support: 'Supporting',
      refute: 'Refuting',
      insufficient: 'Insufficient',
    } satisfies Record<ArticleStance, string>,
    rank: (rank: number | string) => `Rank ${rank}`,
    metadata: (pmid: string, confidence: string) =>
      `PMID ${pmid} · Confidence ${confidence}`,
    evidenceSentenceCount: (count: number) =>
      `${count} evidence sentence${count === 1 ? '' : 's'}`,
    empty: 'No ranked articles were provided for this Claim.',
    pmid: 'PMID',
    stanceConfidence: 'Stance confidence',
    evidenceSentences: 'Evidence sentences',
    rationale: 'Rationale',
    openPubMed: 'Open in PubMed',
    breadcrumbLabel: 'Inspector breadcrumb',
    evidenceSelection: 'Evidence selection',
    section: 'Section',
    sentenceIndex: 'Sentence index',
    evidenceId: 'Evidence ID',
    noCanonicalSpan:
      'No canonical-text span is available for this evidence sentence.',
    sentence: (index: number) => `Sentence ${index}`,
    unlocatedEvidence: (shortId: string) =>
      `${shortId} · Span unavailable`,
    noEvidence:
      'No evidence sentences were linked to this Article.',
    canonicalText: 'Canonical Article Text',
    canonicalTextLabel: 'Canonical Article Text',
    sectionCount: (count: number) =>
      `${count} section${count === 1 ? '' : 's'}`,
    loadingContext: 'Loading Article Context…',
    contextLoadFailed: 'Article Context could not be loaded',
    fingerprint: {
      unavailable: 'Verification unavailable',
      verified: 'Fingerprint verified',
      unverified: 'Fingerprint not verified',
      unavailableDescription:
        'The backend did not provide fingerprint verification status.',
      verifiedDescription:
        'The displayed canonical text matches the evidence artifact used by the analysis.',
      unverifiedDescription:
        'Cross-version fingerprint verification was unavailable; this does not by itself mean the article text is incorrect.',
    },
    applicability: {
      title: 'Article Applicability',
      dimensions: '8 dimensions',
      description: 'How directly this article matches the exact claim.',
      unavailable: 'Article applicability unavailable for this Run.',
      issuesTitle: 'Applicability Issues',
      issuesUnavailable: 'Applicability issues unavailable for this Run.',
      noIssues: 'No explicit applicability issues reported.',
    },
  },
  applicability: {
    dimensions: {
      population_or_species: 'Population or species',
      intervention_or_exposure: 'Intervention or exposure',
      comparator: 'Comparator',
      outcome: 'Outcome',
      direction: 'Direction',
      timeframe: 'Timeframe',
      causal_strength: 'Causal strength',
      prevention_treatment_scope: 'Prevention / treatment scope',
    } satisfies Record<keyof ArticleApplicability, string>,
    statuses: {
      MATCH: 'Match',
      MISMATCH: 'Mismatch',
      NOT_REPORTED: 'Not reported',
      NOT_APPLICABLE: 'Not applicable',
    },
  },
  inspector: {
    emptyTitle: 'Select an analysis element',
    emptyDescription:
      'Choose highlighted statement text, a Claim, an Inference Step, a Gap, an Article, or Evidence.',
    claimSelection: 'Claim selection',
    inferenceSelection: 'Inference selection',
    gapSelection: 'Gap selection',
    inferenceStep: 'Inference Step',
    fields: {
      originalQuote: 'Original quote',
      canonicalClaim: 'Canonical English Claim',
      displayText: 'Display text',
      argumentRole: 'Argument Role',
      evidenceState: 'Evidence State',
      evidenceStatus: 'Evidence Status',
      inferenceIntegrity: 'Inference Integrity',
    },
    argumentAudit: 'Argument Audit',
    affectingSteps: 'Affecting Inference Steps',
    auditUnavailable: 'Argument audit unavailable for this Run.',
    premiseClaims: 'Premise claims',
    conclusionClaim: 'Conclusion claim',
    detectedGaps: 'Detected gaps',
    noGaps: 'No Scope or Causal Gap detected.',
    structuredGap: 'Structured gap',
    directConclusion: 'Direct conclusion',
    downstreamClaims: 'Downstream claims',
    terminalClaims: 'Terminal claims',
    downstreamSteps: 'Downstream inference steps',
    affectsTerminal: 'Affects terminal conclusion',
    affectedDimensions: 'Affected dimensions',
    supportedByPremises: 'Supported by premises',
    unsupportedExtension: 'Unsupported extension',
    whyGap: 'Why this is a gap',
    closureRequirement: 'Evidence needed to close the gap',
    none: 'None',
    legacyEyebrow: 'Inspector',
    legacyTitle: 'Evidence details',
    nothingSelected: 'Nothing selected',
    selected: (kind: string) => `Selected ${kind}`,
    articleLoaded: (articleId: string) =>
      `Article context loaded for ${articleId}.`,
    selectItem:
      'Select a claim, inference step, article, or evidence item.',
    selectAfterRun: 'Select an item after a completed run is loaded.',
  },
  runProgress: {
    label: 'Analysis progress',
    completed: 'Completed',
    stageCount: (count: number) => `· ${count} stages`,
    duration: (duration: string) => `· ${duration}`,
    stageDetails: 'Stage details',
    stageStateTiming: (state: string, duration: string) =>
      `${state} · ${duration}`,
    eyebrow: 'Run progress',
    waiting: 'Waiting to start',
    running: 'Analysis in progress',
    stopped: 'Analysis stopped',
    stageStates: {
      failed: 'failed',
      current: 'current',
      completed: 'completed',
      pending: 'pending',
    },
    completedStagesLabel: 'Completed analysis stages',
    claimProgress: (completed: number, total: number) =>
      `Claim analysis: ${completed} / ${total}`,
  },
  runError: {
    eyebrow: 'Analysis failed',
    title: 'The run could not be completed',
    failedStage: 'Failed stage',
    code: 'Error code',
    message: 'Error message',
    missingMessage: 'The backend did not provide an error message.',
    tryAgain: 'Try Again',
    back: 'Back to New Analysis',
  },
  localization: {
    commonLanguages: [
      '繁體中文（台灣）',
      '简体中文',
      '日本語',
      '한국어',
      'Deutsch',
      'Français',
    ],
    eyebrow: 'Language versions',
    title: 'Localization',
    source: 'Source',
    loading: 'Loading language versions…',
    listLoadFailed: 'Language versions could not be loaded',
    empty: 'No localizations yet.',
    queued:
      ' is waiting to start. Original Analysis remains displayed.',
    running:
      ' is being localized. Original Analysis remains displayed.',
    failedFallback: 'Localization failed',
    missingError: 'The backend did not provide an error message.',
    retryDescription:
      'Original Analysis remains available. Create a new localization to try again.',
    originalDisplayed: 'Original Analysis displayed',
    invalidSelection:
      'The requested localization does not belong to this Run.',
    missingResult:
      'The requested localization completed without a presentation result.',
    targetLabel: 'New target language',
    creating: 'Creating…',
    create: 'Create Localization',
    validation: 'Enter a target language.',
  },
  export: {
    title: 'Export & share',
    originalBoundary:
      'Downloads export the Original Analysis. The backend does not provide localized export endpoints.',
    json: 'Download JSON',
    markdown: 'Download Markdown',
    downloading: 'Downloading…',
    copyLink: 'Copy Run Link',
    linkCopied: 'Link copied',
    jsonFailure: (message: string) => `JSON download failed: ${message}`,
    markdownFailure: (message: string) =>
      `Markdown download failed: ${message}`,
    copyFailure: (message: string) =>
      `Could not copy the link: ${message}`,
  },
  expert: {
    title: 'Expert View',
    subtitle: 'Technical metadata',
    runDetails: 'Run-level Technical Details',
    articleDetails: 'Article-level Technical Details',
    pipelineTimings: 'Pipeline stage timings',
    analysisContext: 'Analysis context',
    modelMetadata: 'Model and artifact metadata',
    retrievalTrace: 'Retrieval and reranking trace',
    evidenceProvenance: 'Evidence provenance',
    columns: {
      stage: 'Stage',
      seconds: 'Seconds',
      method: 'Method',
      rank: 'Rank',
      score: 'Score',
    },
    fields: {
      runId: 'Run ID',
      outputLanguage: 'Output language',
      totalSeconds: 'Total execution time (seconds)',
      schemaVersion: 'Schema version',
      contractId: 'Contract ID',
      localizationId: 'Localization ID',
      localizationTarget: 'Localization target',
      localizationStatus: 'Localization status',
      scope: 'Scope',
      aggregationMethod: 'Aggregation method',
      retrievalMethods: 'Retrieval methods',
      fusionMethod: 'Fusion method',
      reranker: 'Reranker',
      sourceDepth: 'Source depth',
      denseNprobe: 'Dense nprobe',
      rrfK: 'RRF k',
      rerankDepth: 'Rerank depth',
      articleTopK: 'Article top k',
      maxEvidence: 'Max evidence sentences / article',
      providers: 'Providers',
      models: 'Models',
      modelFingerprints: 'Model fingerprints',
      promptVersions: 'Prompt versions',
      statementSha: 'Statement bundle SHA-256',
      inferenceSha: 'Inference gap bundle SHA-256',
      articleNodeId: 'Article node ID',
      articleId: 'Article ID',
      pmid: 'PMID',
      provider: 'Provider',
      model: 'Model',
      modelFingerprint: 'Model fingerprint',
      promptVersion: 'Prompt version',
      stanceConfidence: 'Stance confidence',
      evidenceCount: 'Evidence count',
      canonicalFingerprint: 'Canonical text fingerprint',
      evidenceIds: 'Evidence IDs',
      sourceFingerprints: 'Source text fingerprints',
      splitterFingerprints: 'Splitter fingerprints',
      fingerprintVerified: 'Fingerprint verified',
    },
    methods: {
      bm25: 'BM25 retrieval',
      medcpt: 'MedCPT retrieval',
      bmretriever: 'BMRetriever retrieval',
      rrf: 'RRF fusion',
      crossEncoder: 'Cross-Encoder reranking',
      finalRank: 'Final article rank',
    },
    scoreNote:
      'Retrieval and reranking scores are backend-provided method-specific values and are not combined or interpreted as stance confidence.',
    stages: {
      statement_decomposition: 'Claim decomposition',
      claim_analysis: 'Claim analysis',
      statement_bundle: 'Statement bundle',
      inference_gap_analysis: 'Inference gap analysis',
      output_generation: 'Output generation',
    } satisfies Record<RunStage, string>,
  },
  stageLabels: {
    statement_decomposition: 'Claim 拆解',
    claim_analysis: '證據分析',
    statement_bundle: 'Bundle 建立',
    inference_gap_analysis: 'Gap 分析',
    output_generation: '輸出生成',
  } satisfies Record<RunStage, string>,
  statusLabels: {
    queued: 'queued',
    running: 'running',
    succeeded: 'succeeded',
    failed: 'failed',
  } satisfies Record<RunStatus, string>,
  presentationLabels: {
    scopeGap: 'Scope Gap',
    causalGap: 'Causal Gap',
    notApplicable: 'Not applicable',
    notApplicableCompact: 'N/A',
  },
  toast: {
    viewportLabel: 'Notifications',
    dismiss: (title: string) => `Dismiss ${title}`,
    actionFailed: 'Action could not be completed',
    actionFailedDescription: 'Please try again from the page.',
    analysisCreating: 'Creating analysis',
    analysisCreatingDescription: 'Submitting the biomedical statement.',
    analysisStarted: 'Analysis started',
    analysisStartedDescription: 'The new run has been created.',
    analysisStartFailed: 'Analysis could not be started',
    analysisCompleted: 'Analysis completed',
    analyzedClaims: (count: number) =>
      `${count} claim${count === 1 ? '' : 's'} were analyzed.`,
    resultsReady: 'The analysis results are ready.',
    analysisFailed: 'Analysis failed',
    stoppedDuring: (stage: string) => `The run stopped during ${stage}.`,
    stoppedBeforeComplete:
      'The run stopped before analysis could be completed.',
    localizationCreating: 'Creating localization',
    localizationRequesting: (language: string) =>
      `${language} output is being requested.`,
    localizationStarted: 'Localization started',
    localizationGenerating: (language: string) =>
      `${language} output is being generated.`,
    localizationStartFailed: 'Localization could not be started',
    localizationReady: 'Localization ready',
    localizationDisplayed: (language: string) =>
      `${language} is now displayed.`,
    localizationFailed: 'Localization failed',
    localizationCouldNotGenerate: (language: string) =>
      `${language} could not be generated.`,
    preparingJson: 'Preparing JSON export',
    preparingMarkdown: 'Preparing Markdown export',
    exportPrepared: 'Export prepared',
    jsonStarted: 'Your JSON download has started.',
    markdownStarted: 'Your Markdown download has started.',
    jsonFailed: 'JSON export failed',
    markdownFailed: 'Markdown export failed',
    copied: 'Copied to clipboard',
    copiedDescription: 'The shareable Run link is ready to paste.',
    copyFailed: 'Could not copy the Run link',
  },
  errors: {
    unexpected: 'An unexpected error occurred.',
    operationFailed:
      'The operation could not be completed. Please try again.',
    apiBaseBlank: 'EvidenceGap API base URL must not be blank',
    apiRequestFailed: 'EvidenceGap API request failed',
    toastProviderMissing: 'useToast must be used within ToastProvider',
  },
} as const
