import type {
  ArticleApplicability,
  ArticleStance,
  RunStage,
  RunStatus,
} from './contracts'

export const UI_TEXT = {
  common: {
    unavailable: '不可用',
    dash: '—',
    retry: '重试',
    yes: '是',
    no: '否',
    original: '原始版本',
    claim: '主张',
    article: '文章',
    evidence: '证据',
    sectionUnavailable: '章节不可用',
    spanUnavailable: '文本范围不可用',
    duration: {
      seconds: (seconds: number) => `${seconds.toFixed(1)} 秒`,
      minutes: (minutes: number, seconds: number) =>
        `${minutes} 分 ${String(seconds).padStart(2, '0')} 秒`,
    },
  },
  brand: {
    name: 'EvidenceGap',
    subtitle: '陈述证据分析',
  },
  header: {
    newAnalysis: '新建分析',
    openRecentRuns: '打开最近任务',
    recentRuns: '最近任务',
    status: {
      running: '分析正在运行',
      failed: '任务需要处理',
      loaded: '任务已载入',
      ready: '可以开始分析',
    },
  },
  drawers: {
    newAnalysis: '新建分析',
    closeNewAnalysis: '关闭新建分析',
    recentRuns: '最近任务',
    closeRecentRuns: '关闭最近任务',
  },
  analysisForm: {
    eyebrow: '新建分析',
    title: '分析生物医学陈述',
    statementLabel: '生物医学陈述',
    statementPlaceholder:
      '输入一个或多个生物医学主张或一段论证……',
    languageLabel: '输出语言',
    submit: '分析陈述',
    submitting: '正在创建任务……',
    validation: '请输入要分析的生物医学陈述。',
    languages: [
      { value: 'English', label: '英文原文' },
      { value: '繁體中文（台灣）', label: '繁体中文（台湾）' },
      { value: '简体中文', label: '简体中文' },
      { value: '日本語', label: '日语' },
    ],
  },
  workspace: {
    loadingRun: '正在载入分析任务',
    loadingRunDescription: '正在获取后端的当前状态……',
    runNotFound: '未找到任务',
    runLoadFailed: '无法载入任务',
    resizePanels: '调整图谱工作区与详情面板的大小',
  },
  history: {
    eyebrow: '工作区',
    title: '最近任务',
    loading: '正在载入最近的分析……',
    loadFailed: '无法载入最近任务',
    emptyTitle: '暂无分析',
    emptyDescription:
      '已完成和进行中的任务会显示在这里。',
    metrics: {
      claims: '主张',
      gaps: '缺口',
      time: '耗时',
    },
  },
  graph: {
    eyebrow: '主张图谱',
    noSelection: '尚未选择分析',
    noSelectionDescription:
      '提交一条生物医学陈述，或打开最近的分析。',
    focusModeLabel: '图谱聚焦模式',
    focusModes: {
      all: '全部',
      gaps: '缺口',
      conflicts: '冲突',
    },
    layingOut: '正在布局论证图谱……',
    layoutErrorFallback: '未知的图谱布局错误',
    unavailable: '论证图谱不可用',
    noClaims: '本次分析中没有主张',
    noClaimsDescription:
      '后端返回的展示结果中没有可显示的主张节点。',
    claim: (claimNumber: number) => `主张 ${claimNumber}`,
    claimAria: (claimNumber: number, text: string) =>
      `主张 ${claimNumber}：${text}`,
    inferenceStep: (stepNumber: number) => `推理步骤 ${stepNumber}`,
    inferenceAria: (stepNumber: number) =>
      `推理步骤 ${stepNumber}`,
    inferenceRelation: (premiseCount: number) =>
      `${premiseCount} 个前提 → 1 个结论`,
    retrievedTopArticles: '检索到的首选文章',
    articleCounts: (
      support: number,
      refute: number,
      insufficient: number,
    ) => `支持 ${support} · 反驳 ${refute} · 不足 ${insufficient}`,
    terminalClaim: '终端主张',
  },
  details: {
    eyebrow: '分析工作区',
    title: '详情',
    tabListLabel: '分析详情',
    tabs: {
      overview: '概览',
      inspect: '检查',
      run: '任务',
    },
    noAnalysisTitle: '尚未选择分析',
    noAnalysisDescription:
      '创建一个任务，或从最近任务中选择一个。',
    nothingToInspectTitle: '暂时没有可检查的内容',
    nothingToInspectDescription:
      '分析成功完成后即可检查详细内容。',
    noRunTitle: '尚未选择任务',
    noRunDescription:
      '任务进度、本地化、导出和技术详情会显示在这里。',
    originalStatement: '原始陈述',
    methodologicalBoundary: '方法学边界',
    methodologicalBoundaryItems: [
      '仅总结检索到的首选文章。',
      '不属于系统综述。',
      '不构成临床建议。',
      '不代表最终医学事实。',
    ],
    sourceDepth: (sourceDepth: number, articleTopK: number) =>
      `来源深度：${sourceDepth}；文章 Top K：${articleTopK}。`,
    execution: '执行信息',
    created: '创建时间',
    output: '输出',
    duration: '耗时',
    runId: (runId: string) => `任务 ID：${runId}`,
  },
  summary: {
    eyebrow: '结果概览',
    pending: '分析等待中',
    pendingDescription:
      '分析成功完成后，将显示主张证据和推理完整性。',
    complete: '分析完成',
    headline: (
      claims: number,
      supported: number,
      insufficient: number,
      gaps: number,
    ) =>
      `${claims} 个主张 · ${supported} 个获得支持 · ${insufficient} 个证据不足 · ${gaps} 个缺口`,
    metricsLabel: '分析摘要指标',
    metrics: {
      claims: '主张',
      supported: '获得支持',
      insufficient: '证据不足',
      detectedGaps: '检测到的缺口',
    },
    secondary: {
      refuted: (count: number) => `${count} 个被反驳`,
      conflicted: (count: number) => `${count} 个存在冲突`,
      errors: (count: number) => `${count} 个错误`,
    },
    terminalConclusions: '终端结论',
    terminalUnavailable:
      '本次任务没有可用的双轴终端状态。',
    noTerminalConclusions: '没有终端结论。',
    integrity: {
      claimsIntact: '推理完整的主张',
      claimsGapped: '存在推理缺口的主张',
      stepsIntact: '完整的推理步骤',
      stepsGapped: '存在缺口的推理步骤',
    },
  },
  claims: {
    title: '主张',
    selectSpan: (
      overlapping: boolean,
      text: string,
    ) => `选择${overlapping ? '重叠主张' : '主张'}：${text}`,
  },
  evidenceBalance: {
    title: '证据平衡',
    articleCount: (count: number) =>
      `${count} 篇文章`,
    boundary: '检索到的首选文章分布',
    aria: (support: number, refute: number, insufficient: number) =>
      `${support} 篇支持文章、${refute} 篇反驳文章，以及 ${insufficient} 篇证据不足文章`,
    supporting: '支持',
    refuting: '反驳',
    insufficient: '证据不足',
  },
  articles: {
    rankedTitle: '文章排名',
    boundary: '该主张检索到的首选文章',
    groups: {
      support: '支持',
      refute: '反驳',
      insufficient: '证据不足',
    } satisfies Record<ArticleStance, string>,
    rank: (rank: number | string) => `排名 ${rank}`,
    metadata: (pmid: string, confidence: string) =>
      `PMID ${pmid} · 置信度 ${confidence}`,
    evidenceSentenceCount: (count: number) =>
      `${count} 条证据句`,
    empty: '没有为该主张提供已排名的文章。',
    pmid: 'PMID',
    stanceConfidence: '立场置信度',
    evidenceSentences: '证据句',
    rationale: '判断理由',
    openPubMed: '在 PubMed 中打开',
    breadcrumbLabel: '检查路径',
    evidenceSelection: '证据选择',
    section: '章节',
    sentenceIndex: '句子索引',
    evidenceId: '证据 ID',
    noCanonicalSpan:
      '该证据句没有可用的规范文本范围。',
    sentence: (index: number) => `句子 ${index}`,
    unlocatedEvidence: (shortId: string) =>
      `${shortId} · 文本范围不可用`,
    noEvidence:
      '没有与该文章关联的证据句。',
    canonicalText: '规范文章文本',
    canonicalTextLabel: '规范文章文本',
    sectionCount: (count: number) =>
      `${count} 个章节`,
    loadingContext: '正在载入文章上下文……',
    contextLoadFailed: '无法载入文章上下文',
    fingerprint: {
      unavailable: '验证状态不可用',
      verified: '指纹已验证',
      unverified: '指纹未验证',
      unavailableDescription:
        '后端未提供指纹验证状态。',
      verifiedDescription:
        '当前显示的规范文本与本次分析使用的证据制品一致。',
      unverifiedDescription:
        '无法进行跨版本指纹验证；这本身并不表示文章文本有误。',
    },
    applicability: {
      title: '文章适用性',
      dimensions: '8 个维度',
      description: '该文章与具体主张的直接匹配程度。',
      unavailable: '本次任务没有可用的文章适用性信息。',
      issuesTitle: '适用性问题',
      issuesUnavailable: '本次任务没有可用的适用性问题信息。',
      noIssues: '未报告明确的适用性问题。',
    },
  },
  applicability: {
    dimensions: {
      population_or_species: '人群或物种',
      intervention_or_exposure: '干预或暴露',
      comparator: '对照',
      outcome: '结局',
      direction: '效应方向',
      timeframe: '时间范围',
      causal_strength: '因果强度',
      prevention_treatment_scope: '预防/治疗范围',
    } satisfies Record<keyof ArticleApplicability, string>,
    statuses: {
      MATCH: '匹配',
      MISMATCH: '不匹配',
      NOT_REPORTED: '未报告',
      NOT_APPLICABLE: '不适用',
    },
  },
  inspector: {
    emptyTitle: '选择一个分析元素',
    emptyDescription:
      '请选择高亮的陈述文本、主张、推理步骤、缺口、文章或证据。',
    claimSelection: '主张选择',
    inferenceSelection: '推理选择',
    gapSelection: '缺口选择',
    inferenceStep: '推理步骤',
    fields: {
      originalQuote: '原文引句',
      canonicalClaim: '规范英文主张',
      displayText: '显示文本',
      argumentRole: '论证角色',
      evidenceState: '证据状态',
      evidenceStatus: '证据判定',
      inferenceIntegrity: '推理完整性',
    },
    argumentAudit: '论证审计',
    affectingSteps: '受影响的推理步骤',
    auditUnavailable: '本次任务没有可用的论证审计。',
    premiseClaims: '前提主张',
    conclusionClaim: '结论主张',
    detectedGaps: '检测到的缺口',
    noGaps: '未检测到范围缺口或因果缺口。',
    structuredGap: '结构化缺口',
    directConclusion: '直接结论',
    downstreamClaims: '下游主张',
    terminalClaims: '终端主张',
    downstreamSteps: '下游推理步骤',
    affectsTerminal: '影响终端结论',
    affectedDimensions: '受影响的维度',
    supportedByPremises: '前提所支持的内容',
    unsupportedExtension: '缺乏支持的扩展',
    whyGap: '为何构成缺口',
    closureRequirement: '弥合缺口所需的证据',
    none: '无',
    legacyEyebrow: '检查器',
    legacyTitle: '证据详情',
    nothingSelected: '尚未选择内容',
    selected: (kind: string) => `已选择${kind}`,
    articleLoaded: (articleId: string) =>
      `已载入 ${articleId} 的文章上下文。`,
    selectItem:
      '请选择主张、推理步骤、文章或证据项。',
    selectAfterRun: '载入已完成的任务后，请选择一个项目。',
  },
  runProgress: {
    label: '分析进度',
    completed: '已完成',
    stageCount: (count: number) => `· ${count} 个阶段`,
    duration: (duration: string) => `· ${duration}`,
    stageDetails: '阶段详情',
    stageStateTiming: (state: string, duration: string) =>
      `${state} · ${duration}`,
    eyebrow: '任务进度',
    waiting: '等待开始',
    running: '分析进行中',
    stopped: '分析已停止',
    stageStates: {
      failed: '失败',
      current: '当前',
      completed: '已完成',
      pending: '待处理',
    },
    completedStagesLabel: '已完成的分析阶段',
    claimProgress: (completed: number, total: number) =>
      `主张分析：${completed} / ${total}`,
  },
  runError: {
    eyebrow: '分析失败',
    title: '任务未能完成',
    failedStage: '失败阶段',
    code: '错误代码',
    message: '错误信息',
    missingMessage: '后端未提供错误信息。',
    tryAgain: '重试',
    back: '返回新建分析',
  },
  localization: {
    commonLanguages: [
      '繁體中文（台灣）',
      '简体中文',
      '日本語',
      '한국어',
      'Deutsch',
      'Français',
    ],
    eyebrow: '语言版本',
    title: '本地化',
    source: '来源',
    loading: '正在载入语言版本……',
    listLoadFailed: '无法载入语言版本',
    empty: '暂无本地化版本。',
    queued:
      '正在等待开始。当前仍显示原始分析。',
    running:
      '正在进行本地化。当前仍显示原始分析。',
    failedFallback: '本地化失败',
    missingError: '后端未提供错误信息。',
    retryDescription:
      '原始分析仍然可用。请创建新的本地化版本以重试。',
    originalDisplayed: '当前显示原始分析',
    invalidSelection:
      '请求的本地化版本不属于本次任务。',
    missingResult:
      '请求的本地化任务已经完成，但没有返回展示结果。',
    targetLabel: '新的目标语言',
    creating: '正在创建……',
    create: '创建本地化版本',
    validation: '请输入目标语言。',
  },
  export: {
    title: '导出与分享',
    originalBoundary:
      '下载内容仅导出原始分析。后端目前不提供本地化版本的导出接口。',
    json: '下载 JSON',
    markdown: '下载 Markdown',
    downloading: '正在下载……',
    copyLink: '复制任务链接',
    linkCopied: '链接已复制',
    jsonFailure: (message: string) => `JSON 下载失败：${message}`,
    markdownFailure: (message: string) =>
      `Markdown 下载失败：${message}`,
    copyFailure: (message: string) =>
      `无法复制链接：${message}`,
  },
  expert: {
    title: '专家视图',
    subtitle: '技术元数据',
    runDetails: '任务级技术详情',
    articleDetails: '文章级技术详情',
    pipelineTimings: '流水线阶段耗时',
    analysisContext: '分析上下文',
    modelMetadata: '模型与制品元数据',
    retrievalTrace: '检索与重排轨迹',
    evidenceProvenance: '证据溯源',
    columns: {
      stage: '阶段',
      seconds: '秒',
      method: '方法',
      rank: '排名',
      score: '分数',
    },
    fields: {
      runId: '任务 ID',
      outputLanguage: '输出语言',
      totalSeconds: '总执行时间（秒）',
      schemaVersion: 'Schema 版本',
      contractId: 'Contract ID',
      localizationId: '本地化 ID',
      localizationTarget: '本地化目标语言',
      localizationStatus: '本地化状态',
      scope: '范围',
      aggregationMethod: '聚合方法',
      retrievalMethods: '检索方法',
      fusionMethod: '融合方法',
      reranker: '重排器',
      sourceDepth: '来源深度',
      denseNprobe: 'Dense nprobe',
      rrfK: 'RRF k',
      rerankDepth: '重排深度',
      articleTopK: '文章 Top K',
      maxEvidence: '每篇文章的最大证据句数',
      providers: '提供方',
      models: '模型',
      modelFingerprints: '模型指纹',
      promptVersions: 'Prompt 版本',
      statementSha: '陈述 bundle SHA-256',
      inferenceSha: '推理缺口 bundle SHA-256',
      articleNodeId: '文章节点 ID',
      articleId: '文章 ID',
      pmid: 'PMID',
      provider: '提供方',
      model: '模型',
      modelFingerprint: '模型指纹',
      promptVersion: 'Prompt 版本',
      stanceConfidence: '立场置信度',
      evidenceCount: '证据数量',
      canonicalFingerprint: '规范文本指纹',
      evidenceIds: '证据 ID',
      sourceFingerprints: '来源文本指纹',
      splitterFingerprints: '切分器指纹',
      fingerprintVerified: '指纹已验证',
    },
    methods: {
      bm25: 'BM25 检索',
      medcpt: 'MedCPT 检索',
      bmretriever: 'BMRetriever 检索',
      rrf: 'RRF 融合',
      crossEncoder: 'Cross-Encoder 重排',
      finalRank: '最终文章排名',
    },
    scoreNote:
      '检索与重排分数是后端提供的、与具体方法相关的数值；这些分数不会被合并，也不能解释为立场置信度。',
    stages: {
      statement_decomposition: '主张拆解',
      claim_analysis: '主张分析',
      statement_bundle: '陈述 bundle',
      inference_gap_analysis: '推理缺口分析',
      output_generation: '输出生成',
    } satisfies Record<RunStage, string>,
  },
  stageLabels: {
    statement_decomposition: '主张拆解',
    claim_analysis: '证据分析',
    statement_bundle: 'Bundle 创建',
    inference_gap_analysis: '缺口分析',
    output_generation: '输出生成',
  } satisfies Record<RunStage, string>,
  statusLabels: {
    queued: '排队中',
    running: '运行中',
    succeeded: '已成功',
    failed: '失败',
  } satisfies Record<RunStatus, string>,
  presentationLabels: {
    scopeGap: '范围缺口',
    causalGap: '因果缺口',
    notApplicable: '不适用',
    notApplicableCompact: '不适用',
  },
  toast: {
    viewportLabel: '通知',
    dismiss: (title: string) => `关闭“${title}”`,
    actionFailed: '操作未能完成',
    actionFailedDescription: '请在页面中重试。',
    analysisCreating: '正在创建分析',
    analysisCreatingDescription: '正在提交生物医学陈述。',
    analysisStarted: '分析已开始',
    analysisStartedDescription: '新的分析任务已创建。',
    analysisStartFailed: '无法开始分析',
    analysisCompleted: '分析已完成',
    analyzedClaims: (count: number) =>
      `已分析 ${count} 个主张。`,
    resultsReady: '分析结果已准备就绪。',
    analysisFailed: '分析失败',
    stoppedDuring: (stage: string) => `任务在“${stage}”阶段停止。`,
    stoppedBeforeComplete:
      '任务在分析完成前停止。',
    localizationCreating: '正在创建本地化版本',
    localizationRequesting: (language: string) =>
      `正在请求生成${language}输出。`,
    localizationStarted: '本地化已开始',
    localizationGenerating: (language: string) =>
      `正在生成${language}输出。`,
    localizationStartFailed: '无法开始本地化',
    localizationReady: '本地化版本已就绪',
    localizationDisplayed: (language: string) =>
      `当前显示${language}版本。`,
    localizationFailed: '本地化失败',
    localizationCouldNotGenerate: (language: string) =>
      `无法生成${language}版本。`,
    preparingJson: '正在准备 JSON 导出',
    preparingMarkdown: '正在准备 Markdown 导出',
    exportPrepared: '导出已准备',
    jsonStarted: 'JSON 下载已开始。',
    markdownStarted: 'Markdown 下载已开始。',
    jsonFailed: 'JSON 导出失败',
    markdownFailed: 'Markdown 导出失败',
    copied: '已复制到剪贴板',
    copiedDescription: '可分享的任务链接已经可以粘贴。',
    copyFailed: '无法复制任务链接',
  },
  errors: {
    unexpected: '发生意外错误。',
    operationFailed:
      '操作未能完成，请重试。',
    apiBaseBlank: 'EvidenceGap API 基础 URL 不能为空',
    apiRequestFailed: 'EvidenceGap API 请求失败',
    toastProviderMissing: 'useToast 必须在 ToastProvider 内使用',
  },
} as const
